name: install.sh e2e
on:
  release:
    types: [published]

permissions:
  contents: read


env:
  GITHUB_TOKEN: ${{ secrets.UMF_TOKEN }}
  DEBUG_MODE: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          git config --global user.email test@example.com
          git config --global user.name test
          # private fetch 통과용 https+token 강제
          git config --global url."https://x-access-token:${GITHUB_TOKEN}@github.com/".insteadof "https://github.com/"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - run: sudo apt-get update && sudo apt-get install -y git make wget
      - run: chmod +x scripts/test-install.sh
      - run: scripts/test-install.sh


